use_frameworks!

platform :ios, '10.0'

target 'MAMonitor_Example' do
  #pod 'MAMonitor', :path => '../'
  pod 'MAMonitor',:podspec => '../MAMonitor.podspec'

  target 'MAMonitor_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
